---
- name: Upgrade all packages to the latest version.
  apt:
    name: "*"
    state: latest
  tags: 
    - apt_upgrade

- name: Remove useless packages from the cache.
  apt:
    autoclean: yes
  tags: 
    - apt_upgrade
    - apt_autoclean

- name: Remove dependencies that are no longer required.
  apt:
    autoremove: yes
  tags: 
    - apt_upgrade
    - apt_autoremove

- name: Update all packages to the latest version.
  apt:
    upgrade: dist
  tags: apt_dist_upgrade