---
- import_tasks: kernel.yml

# https://www.reddit.com/r/BOINC/comments/g0r0wa/running_rosetta_covid19_workunits_on_raspberry_pi/
- name: copy zram.sh.
  copy:
    src: usr/bin/zram.sh
    dest: /usr/bin/zram.sh
    backup: yes
    owner: root
    group: root
    mode: 0755
  tags: boinc_setup

- name: add line to run zram.sh script on boot.
  lineinfile:
    state: present
    dest: /etc/rc.local
    insertbefore: '^exit 0'
    line: /usr/bin/zram.sh &
  tags: boinc_setup

- name: install boinc client.
  apt:
    name: ['boinc-client', 'boinctui']
    state: latest
  tags:
    - boinc_setup

- name: insert options to cc_config.xml and global_prefs_override.xml
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
    owner: root
    group: root
  with_items:
    - { src: etc/boinc-client/cc_config.xml, dest: /etc/boinc-client }
    - { src: etc/boinc-client/global_prefs_override.xml, dest: /etc/boinc-client }
    - { src: etc/boinc-client/gui_rpc_auth.cfg, dest: /etc/boinc-client }
  tags: boinc_setup
  notify: restart_boinc-client
